# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Open Geneva
email: hello@opengeneva.org
description: A Festival of Open Innovation for Science, Technology and Society
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opengeneva.org" # the base hostname & protocol for your site
twitter_username: opengeneva
github_username:  opengeneva
linkedin_username: opengeneva
youtube_username: opengeneva
facebook_username: opengeneva
port : 4001

site.google_analytics : UA-114211038-1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

excerpt_separator: <!--more-->

collections:
  events :
    output : true

t:
  en:
    home:
      name: "News"
      url: "/"
      display : false
    program :
      name: "Program"
      url: "/program/"
      display : true
    hackathons:
      name: "Hackathons"
      url : "/hackathons/"
      display : true
    hackshow :
      name: "Hackshow"
      url: "/hackshow/"
      display : true
    timeline :
      name: "Timeline"
      url: "/timeline/"
      display : false
    register:
      name: "Register"
      url : "/register/"
      display : false
    archive :
      name : "Archive"
      url: "/archive/"
      display : false
    about:
      name: "About"
      url: "/about/"
      display : true
    baseline: "<strong>An Open Innovation Festival</strong> <br> for science, technology & society"
    repost : "original post"
    main_partners : "Main Partners"
    acceleration_partners: "Acceleration Partners"
    academic_partners : "Academic Partners"

  fr:
    home:
      name: "Accueil"
      url: "/accueil/"
      display : false
    program :
      name: "Programme"
      url: "/program/"
      display : true
    hackathons:
      name: "Hackathons"
      url : "/hackathons/"
      display : true
    hackshow :
      name: "Hackshow"
      url: "/hackshow_fr/"
      display : true
    timeline :
      name: "Déroulement"
      url: "/deroulement/"
      display : false
    register:
      name: "Participer"
      url : "/participer/"
      display : false
    archive:
      name : "Archives"
      url : "/archives/"
      display : false
    about:
      name: "À propos"
      url: "/apropos/"
      display : true
    media:
      name: "Media"
      url : "/media/"
      display : false
    baseline: "<strong>Festival d'Innovation Ouverte</strong> <br>science, technologie & société"
    repost: "post original"
    main_partners : "Partenaires Principaux"
    acceleration_partners: "Partenaires Accélération"
    academic_partners : "Partneraires Académiques"

  zh:
     home:
       name: "Home"
       url: "/活动进展/"
       display : false
     program :
       name: "Program"
       url: "/program/"
       display : false
     timeline :
       name: "活动进展"
       url: "/活动进展/"
       display : true
     register:
       name: "Register"
       url : "/register/"
       display : false
     archive :
       name : "当年今日"
       url: "/当年今日/"
       display : false
     about:
       name: "关于我们"
       url: "/关于我们/"
       display : true
     media:
      name: "Media"
      url : "/media_fr/"
      display : false
     baseline: "<strong>An Open Innovation Festival</strong> <br> for science, technology & society"
